### ISSUE TITLE
Loaded the game system. Create new Protagonist, the character sheet is empty. 

### ISSUE THREAD

**Issue by mds0001** [foundryvtt/crucible#20]
![image](https://github.com/user-attachments/assets/366ff113-87bd-4dd2-b587-dc4a93876d1f)

**Comment by aaclayton** [comment]
Crucible version `0.5.x` is not compatible with Foundry VTT version 12, but release `0.6.0` is coming TODAY which adds a ton of changes and V12 compatibility.
